name: food_app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  gap: ^3.0.1
  dio: ^5.4.1
  logger: ^2.0.2+1
  flutter_riverpod: ^2.5.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.7

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    # - assets/images/

  fonts:
    - family: BrandonGrotesque
      fonts:
        - asset: assets/fonts/brandon-grotesque-regular.otf
        - asset: assets/fonts/brandon-grotesque-regular-italic.otf
          style: italic

    - family: BrandoGrotesqueBold
      fonts:
        - asset: assets/fonts/brandon-grotesque-bold.otf
        - asset: assets/fonts/brandon-grotesque-bold-italic.otf
          style: italic
